name: Test symbolic classification on PMLB datataset

env: 
  CACHE_NUMBER: 0

on:
  workflow_dispatch:
    inputs:
      datasets:
        description: "List of Datasets"
        type: choice
        default: all
        options:
          - all
          - GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1
          - GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1
          - GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1
          - GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1
          - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001
          - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001
          - Hill_Valley_with_noise
          - Hill_Valley_without_noise
          - adult
          - agaricus_lepiota
          - chess
          - churn
          - clean2
          - coil2000
          - credit_g
          - dis
          - flare
          - german
          - hypothyroid
          - kr_vs_kp
          - magic
          - mofn_3_7_10
          - mushroom
          - parity5+5
          - phoneme
          - ring
          - spambase
          - twonorm
      estimator:
        description: "Tested classification estimator"
        type: choice
        default: "DecisionTree"
        options:
          - RILS-ROLS
          - HROCH
          - CatBoost
          - GradientBoosting
          - LGBM
          - XGB
          - DecisionTree
          - LogisticRegression
          - KNeighbors
          - RandomForest
          # - SVC

defaults:
  run:
    shell: bash
    working-directory: /home/runner/work/
  
jobs:
  cache_env:
    runs-on: ubuntu-latest
    steps:
      - name: Cache enviroment
        uses: actions/cache@v3
        with:
          path:  /home/runner/work/classification_test/classification_test/test_env
          key: ${{ runner.os }}-env
        id: cache
        
      - name: Install enviroment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
                echo "Install enviroment"
                cd classification_test
                git clone --depth 1 --branch main https://github.com/janoPig/classification_test.git temp_directory
                mv temp_directory/* classification_test
                rm -rf temp_directory
                cd classification_test
                ./install_requirements.sh
                ./install_estimators.sh

  pmlb_test:
    needs: cache_env
    strategy:
      matrix:
        seed: [0, 1, 2, 3, 4]
        dataset:
          - GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1
          - GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1
          - GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1
          - GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1
          - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001
          - GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001
          - Hill_Valley_with_noise
          - Hill_Valley_without_noise
          - adult
          - agaricus_lepiota
          - chess
          - churn
          - clean2
          - coil2000
          - credit_g
          - dis
          - flare
          - german
          - hypothyroid
          - kr_vs_kp
          - magic
          - mofn_3_7_10
          - mushroom
          - parity5+5
          - phoneme
          - ring
          - spambase
          - twonorm
    env:
      SEED: ${{ matrix.seed }}
      DATASET: ${{ matrix.dataset }}
      ESTIMATOR: ${{ github.event.inputs.estimator }}
      NO_SKIP: ${{ github.event.inputs.datasets == 'all' || github.event.inputs.datasets == matrix.dataset }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Cache enviroment
        if: env.NO_SKIP == 'true'
        uses: actions/cache@v3
        with:
          path:  /home/runner/work/classification_test/classification_test/test_env
          key: ${{ runner.os }}-env
        id: cache

      - name: PMLB experiment
        if: env.NO_SKIP == 'true'
        run: |
                echo "PMLB experiment "$DATASET
                lscpu
                mkdir -p output/output
                cd classification_test

                git clone --depth 1 --branch main https://github.com/janoPig/classification_test.git temp_directory
                mkdir -p classification_test
                mv temp_directory/* classification_test
                # activate enviroment
                source ./classification_test/test_env/bin/activate

                # run experiment...
                cd classification_test
                python3 ./code/evaluate.py --estimator $ESTIMATOR --dataset_name $DATASET --random_seed $SEED --out_dir /home/runner/work/output/output

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pmlb_experiment_${{ github.event.inputs.estimator }}
          path: |
            /home/runner/work/output
